apiVersion: v1
kind: Secret
metadata:
  name: financeflow-secrets
  namespace: financeflow
type: Opaque
stringData:
  DB_USERNAME: "postgres"
  DB_PASSWORD: "ProdSecurePassword2026!"
  JWT_SECRET: "FinanceFlow_Super_Secret_Key_2026_BankGrade_Secure_Enterprise_JWT_Token_Key"
